[package]
name = "rust_nma"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras =  { version = "0.28.1", features = ["all_loaders"] }
image = { version = "0.25.2", features = ["jpeg", "png"] }
rand = "0.6.0"